name: Run Batch Prediction

on:
  schedule:
    # Runs at 09:45 PM Pakistan Time (PST), which is 4:45 PM UTC
    - cron: '30 18 * * *'

jobs:
  batch-prediction:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the batch prediction script
      - name: Run batch predictions
        run: |
          python app.py
