name: Run Batch Prediction

on:
  schedule:
    - cron: '24 11 * * *'  

jobs:
  batch-prediction:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the Flask API in the background
      - name: Start Flask API
        run: |
          nohup python app.py &

      # Run the batch prediction script to call the API
      - name: Run batch predictions
        run: |
          python batch_predict.py
